<Project Sdk="MSTest.Sdk">

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fylum.AppHost\Fylum.AppHost.csproj" />
    <ProjectReference Include="..\Fylum.Client\Fylum.Client.csproj" />
  </ItemGroup>

</Project>
