version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: "cron"
    cronjob: "15 4 * * *" # every day 04:15 UTC
  open-pull-requests-limit: 10
  assignees:
  - Muckenbatscher
  labels:
  - Dependencies
  groups:
    aspire:
      patterns:
        - "Aspire*"
    fastendpoints:
      patterns:
        - "FastEndpoints*"
    opentelemetry:
      patterns:
        - "OpenTelemetry*"
    mstest:
      patterns:
        - "MSTest*"
    core:
      patterns:
        - "Microsoft*"
        - "System*"
  ignore:
      - dependency-name: "Scalar.AspNetCore"
        update-types: ["version-update:semver-patch"] # updated very frequently
