version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - Muckenbatscher
  groups:
    aspire:
      patterns:
        - "Aspire*"
    fastendpoints:
      patterns:
        - "FastEndpoints*"
    opentelemetry:
      patterns:
        - "OpenTelemetry*"
    core:
      patterns:
        - "Microsoft*"
        - "System*"
