<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="FastEndpoints" />
		<PackageReference Include="FastEndpoints.Security" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" VersionOverride="8.19.2" />
		<PackageReference Include="Npgsql" />
	</ItemGroup>
	
</Project>
