<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="FastEndpoints" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Fylum.Folders.SharedModels\Fylum.Folders.SharedModels.csproj" />
	  <ProjectReference Include="..\Fylum.Folders.Application\Fylum.Folders.Application.csproj" />
	</ItemGroup>
</Project>
