<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.Testing" />
		<PackageReference Include="MessagePack" />
		<PackageReference Include="Microsoft.Extensions.Http.Resilience" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Source\Fylum.AppHost\Fylum.AppHost.csproj" />
		<ProjectReference Include="..\..\Source\Fylum.Client\Fylum.Client.csproj" />
	</ItemGroup>
</Project>
