<Project Sdk="MSTest.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Http" />
	  <PackageReference Include="NetArchTest.Rules" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Source\Fylum.Migrations.Api\Fylum.Migrations.Api.csproj" />
		<ProjectReference Include="..\Fylum.ArchitectureTest.Common\Fylum.ArchitectureTest.Common.csproj" />
	</ItemGroup>
</Project>
