<Project Sdk="Aspire.AppHost.Sdk">
	
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<UserSecretsId>1b2fd03d-8d27-4eea-b292-f3d705dd8552</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.Docker" />
		<PackageReference Include="Aspire.Hosting.PostgreSQL" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Fylum.Api\Fylum.Api.csproj" />
		<ProjectReference Include="..\Fylum.Migrations.SharedModels\Fylum.Migrations.SharedModels.csproj" IsAspireProjectResource="false" />
		<ProjectReference Include="..\Fylum.Migrations.Api\Fylum.Migrations.Api.csproj" />
		<ProjectReference Include="..\Fylum.Migrations.Web\Fylum.Migrations.Web.csproj" />
		<ProjectReference Include="..\Fylum.Web\Fylum.Web.csproj" />
	</ItemGroup>

</Project>
